package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"crypto/rand"
	"fmt"
	"math/big"
	"time"
	"wireman/graph/model"
)

// CreateArticle is the resolver for the createArticle field.
func (r *mutationResolver) CreateArticle(ctx context.Context, input model.NewArticle) (*model.Article, error) {
	panic(fmt.Errorf("not implemented: CreateArticle - createArticle"))
}

// Articles is the resolver for the articles field.
func (r *queryResolver) Articles(ctx context.Context) ([]*model.Article, error) {
	var arr []*model.Article
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	currentTime := time.Now()
	article1 := &model.Article{
		Title:   "Test Article Title",
		ID:      fmt.Sprintf("T%d", randNumber),
		Type:    model.ArticleStyleGreenViper,
		Date:    currentTime.String(),
		Caption: "Text Caption",
		Link:    "https://google.com",
	}

	return append(arr, article1), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
